---
title: "R Notebook"
output: html_notebook
---

```{r}

library(dplyr)
```


```{r}
players=read.csv("FIFA.csv")

players_2=players[,c("Position","Crossing", "Finishing","Heading.Accuracy","Short.Passing", "Volleys", "Dribbling", "Curve",              "FK.Accuracy","Long.Passing", "Ball.Control", "Acceleration", "Sprint.Speed","Agility","Reactions","Balance","Shot.Power","Jumping",   "Stamina","Strength","Long.Shots", "Aggression", "Interceptions", "Positioning","Vision","Penalties", "Composure",               "Defensive.Awareness", "Standing.Tackle", "Sliding.Tackle")]
colnames(players_2)
```
```{r}
players_2
```
```{r}
Attack=c("LW", "LF", "RW","RF", "CF", "ST", "CAM")
Defense=c("RB", "RWB", "LB", "LWB", "CB")
index_attack=which(players_2$Position %in%(Attack))
index_attack
players_2[index_attack, "Position"]="A"
players_2

index_defense=which(players_2$Position %in%(Defense))
index_defense
players_2[index_defense, "Position"]="D"
players_2=players_2[c(index_attack,index_defense),]
players_2
```

Séparation en jeu de données test et validation
```{r}
n=length(players_2[,1])
len.app=as.integer(3*n/4)
tirage=sample(seq(1,n),len.app, replace=FALSE)
train=players_2[tirage,]
x_train= train[,2:length(train[1,])]
y_train= train[,1]
test=players_2[-tirage,]
x_test= test[,2:length(test[1,])]
y_test= test[,1]

```



```{r}
#install.packages("keras")
library(keras)
```

```{r}
single_perceptron<-function(activation='sigmoid'){
    model = tf.keras.Sequential()
    model %>% layers_dense(1, activation=activation, input_shape=(length(x_train[,1],)))
return(model)
}

```

## SVM

On considère les données sont non-séparables

```{r}
library(e1071)
```


```{r}
svm_player <- train
svm_player$Position <- as.factor(svm_player$Position)
mod.svm.lin = svm(Position~.,data=svm_player,kernel="linear",cost=1)
plot(mod.svm.lin,data = svm_player, Crossing~Finishing)
